# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c

    # - name: Install UPX
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y upx
    - name: Get Tag
      id: get_tag
      run: echo "::set-output name=VERSION::$(cat version.txt)"

    - name: Build
      run: |
        export ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}
        export GO111MODULE=on

        wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
        tar -xf upx-4.2.4-amd64_linux.tar.xz
        export PATH=$(pwd)/upx-4.2.4-amd64_linux:$PATH
        
        ./build-android.sh $(cat frpVersion.txt)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.get_tag.outputs.VERSION }}
          release_name: Auto Release ${{ steps.get_tag.outputs.VERSION }}
          draft: true
          prerelease: false

    - name: Upload files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_tag.outputs.VERSION }}
      run: |
        cd frp/bin/upx/
        for file in *; do
          if [[ -f ${file} ]]; then
              echo "Uploading $file"
              gh release upload "$VERSION" "$file" --repo ${{ github.repository }}
          fi
        done
    - name: Bin Files Hash
      run: |
        go run genDownloadConfig.go -d ./frp/bin/upx
